import { Building2, GitBranch, Layers, ListTodo } from 'lucide-react';

export const HORIZONS = [
    { value: 'h1', label: 'H1 — Core', sub: 'Protect & extend current franchises', accent: '#4a90b8' },
    { value: 'h2', label: 'H2 — Growth', sub: 'Build & scale emerging businesses', accent: '#c9a87c' },
    { value: 'h3', label: 'H3 — Future', sub: 'Explore & incubate future options', accent: '#c87e9d' },
];

export const LEVEL_CONFIGS = {
    portfolio: {
        label: 'Portfolio',
        sub: 'Strategic Themes',
        singular: 'Theme',
        entity: 'Objective',
        labelKey: 'name',
        icon: Building2,
        accent: '#1e3a5a',
        groupKey: 'type',
        groups: [
            { value: 'growth', label: 'Growth', accent: '#c9a87c' },
            { value: 'retention', label: 'Retention', accent: '#4a90b8' },
            { value: 'revenue', label: 'Revenue', accent: '#7ec8a8' },
            { value: 'community', label: 'Community', accent: '#c87e9d' },
        ],
        horizons: HORIZONS,
        statuses: [
            { value: 'funnel', label: 'Funnel', color: '#5d7a94' },
            { value: 'analyzing', label: 'Analyzing', color: '#c9a87c' },
            { value: 'implementing', label: 'Implementing', color: '#4a90b8' },
            { value: 'done', label: 'Done', color: '#7ec8a8' },
        ],
        hasMatrix: true,
        hasTypeFilter: false,
    },
    solution: {
        label: 'Solution Train',
        sub: 'Initiatives',
        singular: 'Initiative',
        entity: 'Initiative',
        labelKey: 'name',
        icon: GitBranch,
        accent: '#4a90b8',
        groupKey: 'type',
        groups: [
            { value: 'feature', label: 'Features', accent: '#c9a87c' },
            { value: 'platform', label: 'Platform', accent: '#4a90b8' },
            { value: 'operations', label: 'Operations', accent: '#7ec8a8' },
            { value: 'research', label: 'Research', accent: '#c87e9d' },
        ],
        horizons: HORIZONS,
        statuses: [
            { value: 'funnel', label: 'Funnel', color: '#5d7a94' },
            { value: 'reviewing', label: 'Reviewing', color: '#c9a87c' },
            { value: 'analyzing', label: 'Analyzing', color: '#4a90b8' },
            { value: 'portfolio_backlog', label: 'Backlog', color: '#5d7a94' },
            { value: 'implementing', label: 'Implementing', color: '#4a90b8' },
            { value: 'done', label: 'Done', color: '#7ec8a8' },
        ],
        hasMatrix: true,
        hasTypeFilter: false,
    },
    program: {
        label: 'ART',
        sub: 'Epics',
        singular: 'Epic',
        entity: 'RoadmapItem',
        labelKey: 'title',
        icon: Layers,
        accent: '#c9a87c',
        groupKey: 'type',
        groups: [
            { value: 'feature', label: 'Features', accent: '#c9a87c' },
            { value: 'enhancement', label: 'Enhancements', accent: '#4a90b8' },
            { value: 'bug', label: 'Bugs', accent: '#c87e9d' },
            { value: 'feedback', label: 'Feedback', accent: '#7ec8a8' },
        ],
        statuses: [
            { value: 'backlog', label: 'Backlog', color: '#5d7a94' },
            { value: 'next_up', label: 'Next Up', color: '#c9a87c' },
            { value: 'in_progress', label: 'In Progress', color: '#4a90b8' },
            { value: 'done', label: 'Done', color: '#7ec8a8' },
        ],
        hasMatrix: true,
        hasTypeFilter: true,
    },
    team: {
        label: 'Team',
        sub: 'Stories',
        singular: 'Story',
        entity: 'Story',
        labelKey: 'title',
        icon: ListTodo,
        accent: '#7ec8a8',
        groupKey: 'type',
        groups: [
            { value: 'frontend', label: 'Frontend', accent: '#c9a87c' },
            { value: 'backend', label: 'Backend', accent: '#4a90b8' },
            { value: 'design', label: 'Design', accent: '#7ec8a8' },
            { value: 'devops', label: 'DevOps', accent: '#c87e9d' },
        ],
        statuses: [
            { value: 'todo', label: 'To Do', color: '#5d7a94' },
            { value: 'in_progress', label: 'In Progress', color: '#4a90b8' },
            { value: 'done', label: 'Done', color: '#7ec8a8' },
            { value: 'blocked', label: 'Blocked', color: '#c87e9d' },
        ],
        hasMatrix: true,
        hasTypeFilter: false,
    },
};

export const TRACEABILITY = {
    portfolio: {
        childLevel: 'solution',
        childEntity: 'Initiative',
        childLabelKey: 'name',
        childLinkField: 'objective_id',
    },
    solution: {
        parentLevel: 'portfolio',
        parentEntity: 'Objective',
        parentLabelKey: 'name',
        parentLinkField: 'objective_id',
        childLevel: 'program',
        childEntity: 'RoadmapItem',
        childLabelKey: 'title',
        childLinkField: 'initiative_id',
    },
    program: {
        parentLevel: 'solution',
        parentEntity: 'Initiative',
        parentLabelKey: 'name',
        parentLinkField: 'initiative_id',
        childLevel: 'team',
        childEntity: 'Story',
        childLabelKey: 'title',
        childLinkField: 'roadmap_item_id',
    },
    team: {
        parentLevel: 'program',
        parentEntity: 'RoadmapItem',
        parentLabelKey: 'title',
        parentLinkField: 'roadmap_item_id',
    },
};

export const LEVEL_ORDER = ['portfolio', 'solution', 'program', 'team'];