import { useState, useEffect } from 'react';
import { InvokeLLM } from '@/integrations/Core';
import { Feedback } from '@/entities/Feedback';
import { useToast } from "@/components/ui/use-toast";
import { 
  X, 
  Brain, 
  Loader2, 
  Sparkles,
  ChevronRight,
  Send,
  UserPlus,
  FilePlus
} from 'lucide-react';

const ACTION_ICONS = {
  create_task: FilePlus,
  assign_owner: UserPlus,
  send_notification: Send,
  default: Sparkles
};

export default function BlockerResolutionWizard({ isOpen, onClose, blockerItem }) {
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [actionInProgress, setActionInProgress] = useState(null);
  const { toast } = useToast();

  useEffect(() => {
    if (isOpen && blockerItem) {
      runAnalysis();
    } else {
      setAnalysis(null); // Reset when closed or no item
    }
  }, [isOpen, blockerItem]);

  const runAnalysis = async () => {
    setLoading(true);
    try {
      const prompt = `You are Lt. Perry, a senior systems engineer and problem-solver. A critical release blocker has been detected. 

**Blocker:** "${blockerItem.text}"
**Source:** ${blockerItem.source}

Analyze this problem. Provide a concise root cause diagnosis and suggest up to 3 concrete, actionable solutions. For each solution, provide a short title, a description of the action, and a technical action_key from this list: [create_task, assign_owner, send_notification].`;

      const result = await InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            root_cause_diagnosis: {
              type: "string",
              description: "A brief, insightful diagnosis of the likely root cause."
            },
            suggested_solutions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  title: { type: "string" },
                  description: { type: "string" },
                  action_key: { type: "string", enum: ["create_task", "assign_owner", "send_notification"] }
                },
                required: ["title", "description", "action_key"]
              }
            }
          },
          required: ["root_cause_diagnosis", "suggested_solutions"]
        }
      });
      setAnalysis(result);
    } catch (error) {
      console.error("Lt. Perry analysis failed:", error);
      toast({
        variant: "destructive",
        title: "Analysis Failed",
        description: "Lt. Perry could not analyze the blocker. Please resolve manually.",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleAction = async (solution) => {
    setActionInProgress(solution.title);
    try {
      // Simulate action based on key
      switch (solution.action_key) {
        case 'create_task':
          // In a real scenario, this would create a Feedback or Task entity
          await Feedback.create({
            type: 'bug_report',
            subject: `[Blocker] ${blockerItem.text}`,
            description: `Generated by Lt. Perry to resolve release blocker: ${solution.description}`,
            priority: 'critical',
            user_email: 'lt.perry@system.ai',
          });
          toast({
            title: "Task Created",
            description: `A critical priority task has been added to the backlog.`,
          });
          break;
        case 'assign_owner':
          // Simulate assigning an owner
          await new Promise(res => setTimeout(res, 1000));
          toast({
            title: "Owner Assigned",
            description: `The appropriate team has been notified to take ownership.`,
          });
          break;
        case 'send_notification':
          // Simulate sending a high-priority notification
          await new Promise(res => setTimeout(res, 1000));
          toast({
            title: "Notification Sent",
            description: `A high-priority alert has been sent to stakeholders.`,
          });
          break;
        default:
          throw new Error("Unknown action key");
      }
      onClose(); // Close wizard on successful action
    } catch (error) {
      console.error(`Failed to execute action '${solution.title}':`, error);
      toast({
        variant: "destructive",
        title: "Action Failed",
        description: "Could not complete the selected action.",
      });
    } finally {
      setActionInProgress(null);
    }
  };

  if (!isOpen || !blockerItem) return null;

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
      <div className="bg-gradient-to-br from-gray-900 via-slate-900 to-black rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden border border-white/20">
        <div className="p-6 border-b border-white/10 flex justify-between items-center">
          <div>
            <h2 className="text-xl font-bold text-white">Blocker Resolution</h2>
            <p className="text-sm text-gray-400">"{blockerItem.text}"</p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-white/10 rounded-lg transition-all"
          >
            <X className="w-5 h-5 text-gray-300" />
          </button>
        </div>

        <div className="p-6 max-h-[70vh] overflow-y-auto">
          {loading && (
            <div className="text-center py-10">
              <Loader2 className="w-10 h-10 animate-spin text-purple-400 mx-auto mb-4" />
              <p className="text-lg text-gray-300">Lt. Perry is analyzing the blocker...</p>
            </div>
          )}

          {analysis && (
            <div className="space-y-6">
              <div>
                <div className="flex items-center gap-3 mb-3">
                  <Brain className="w-6 h-6 text-purple-400" />
                  <h3 className="text-lg font-semibold text-white">Root Cause Diagnosis</h3>
                </div>
                <p className="text-gray-300 bg-black/20 p-3 rounded-lg border border-white/10">
                  {analysis.root_cause_diagnosis}
                </p>
              </div>

              <div>
                <div className="flex items-center gap-3 mb-3">
                  <Sparkles className="w-6 h-6 text-blue-400" />
                  <h3 className="text-lg font-semibold text-white">Suggested Action Plan</h3>
                </div>
                <div className="space-y-3">
                  {analysis.suggested_solutions.map((solution, index) => {
                    const Icon = ACTION_ICONS[solution.action_key] || ACTION_ICONS.default;
                    const isRunning = actionInProgress === solution.title;
                    return (
                      <button
                        key={index}
                        onClick={() => handleAction(solution)}
                        disabled={!!actionInProgress}
                        className="w-full text-left p-4 rounded-lg border border-white/10 bg-white/5 hover:bg-white/10 disabled:opacity-50 disabled:cursor-not-allowed transition-all group"
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-1">
                              <Icon className="w-5 h-5 text-blue-400" />
                              <h4 className="font-semibold text-white">{solution.title}</h4>
                            </div>
                            <p className="text-sm text-gray-400">{solution.description}</p>
                          </div>
                          <div className="ml-4">
                            {isRunning ? (
                              <Loader2 className="w-5 h-5 animate-spin text-blue-400" />
                            ) : (
                              <ChevronRight className="w-5 h-5 text-gray-500 group-hover:text-white transition-all" />
                            )}
                          </div>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}