export const CAMPAIGNS = {
  'C-01': {
    id: 'C-01',
    title: 'The Right Stuff',
    archetype: 'Test Pilot',
    primaryStats: ['VELOCITY', 'RESILIENCE', 'MANEUVER'],
    setting: 'Edwards Air Force Base, Mojave Desert',
    tagline: 'Speed versus survival. The machine versus the human. The record versus the pilot.',
    badge: '✈',
    available: true,
    baseStats: {
      altitude: 10, velocity: 12, payload: 10, range: 9, resilience: 11, maneuver: 10,
    },
    scenes: [
      {
        id: 'prologue',
        type: 'choice',
        title: 'First Flight',
        beat: 'Prologue',
        aiGenerated: false,
        text: `The Mojave desert at 5 AM smells like jet fuel and possibility. You've been assigned to the X-program—the elite test pilot cadre at Edwards. Before your first official flight brief, the chief test pilot, Col. Hargrove, asks you one question over bad coffee in the ready room:\n\n"How'd you end up here?"`,
        choices: [
          {
            key: 'engineering',
            label: 'Engineering scholarship. I wanted to understand the machine before I flew it.',
            statDeltas: { payload: 2, velocity: -1, altitude: 1 },
          },
          {
            key: 'military',
            label: 'Military academy. I flew because I had to. Now I can\'t stop.',
            statDeltas: { resilience: 2, maneuver: 1, range: -1 },
          },
        ],
      },
      {
        id: 'scene1',
        type: 'choice',
        title: 'The Brief',
        beat: 'Scene 1',
        aiGenerated: false,
        text: `The X-29A. Forward-swept wings, digital fly-by-wire, aerodynamically unstable by design. The flight envelope card is 47 pages. Briefing is at 0600.\n\nYour co-pilot Mara Grayson has flown it twelve times. "The sim doesn't prepare you for the feedback rate," she says. "You have to feel it." There are four hours before you strap in.`,
        choices: [
          {
            key: 'manual',
            label: 'Study the manual. Every system. Every limit. You fly the numbers.',
            statDeltas: { payload: 2, maneuver: -1, velocity: 1 },
          },
          {
            key: 'instincts',
            label: 'Spend the time in the cockpit mock-up. Hands on everything. You fly by feel.',
            statDeltas: { maneuver: 2, velocity: 1, payload: -1 },
          },
        ],
      },
      {
        id: 'scene2',
        type: 'choice',
        title: 'The Mach Run',
        beat: 'Scene 2',
        aiGenerated: true,
        fallbackText: `The altimeter reads 52,000 feet. The Mojave is a brown postage stamp below you. You've been climbing through Mach 1.4 when the engine temperature gauge creeps into the yellow. Not red. Yellow.\n\nThe flight test engineer in your ear: "We're showing elevated EGT. Your call, pilot."\n\nPush through to Mach 1.8 and hold the data point, or pull back and live to fly tomorrow.`,
        choices: [
          {
            key: 'throttle',
            label: 'Full throttle. The data point is the mission. Yellow isn\'t red.',
            statDeltas: { velocity: 2, resilience: 1, payload: -1 },
          },
          {
            key: 'pullback',
            label: 'Controlled reduction. Live to fly the next envelope expansion.',
            statDeltas: { payload: 2, altitude: 1, velocity: -1 },
          },
        ],
      },
      {
        id: 'signal_log',
        type: 'signal_log',
        title: 'Save Your Progress',
        beat: 'Scene 3',
      },
      {
        id: 'scene4',
        type: 'choice',
        title: 'The Mentor',
        beat: 'Scene 4',
        aiGenerated: true,
        fallbackText: `Three days after the Mach run, retired test pilot Dr. Jacqueline Cochran—who once held the women's airspeed record and broke it four times—shows up unannounced at the ready room. She's consulting for the program.\n\nShe sits across from you with coffee. "You made the right call up there," she says. "Or the wrong one. Depends what you're optimizing for." She slides a notebook across the table. It's full of margins-notes from thirty years of envelope expansions.\n\n"Read it, or don't. Your call."`,
        choices: [
          {
            key: 'wisdom',
            label: 'Take the notebook. Read every page that night.',
            statDeltas: { payload: 2, range: 2, altitude: 1 },
          },
          {
            key: 'challenge',
            label: '"I appreciate it. But I need to build my own instincts." Push the notebook back.',
            statDeltas: { maneuver: 2, velocity: 1, resilience: 1 },
          },
        ],
      },
      {
        id: 'boss',
        type: 'boss',
        title: 'The Flame-Out',
        beat: 'Boss Moment',
        rollStats: ['resilience', 'maneuver'],
        setup: `At 73,000 feet, the left engine dies.\n\nNo warning. One second the sky is yours. The next, you're in a 90-degree dive at Mach 2.3 with one engine, a compromised hydraulics system, and a ground that's getting very specific.\n\nThe book says eject. Your stats say otherwise.`,
        rollLabel: 'Roll RESILIENCE + MANEUVER',
        fallbackOutcomes: {
          critical_success: 'You execute a textbook single-engine recovery. The aircraft responds. You bring it home at 200 knots on one engine. The flight test community will talk about this for years.',
          success: 'You fight the aircraft for 47 seconds. It cooperates, mostly. You land hard, gear intact, adrenaline at maximum. Damaged aircraft, intact pilot. That\'s a win.',
          fail: 'You almost save it. The aircraft departs controlled flight at 8,000 feet. You eject cleanly. The X-29A becomes a footnote in the accident database. You become a cautionary tale—the kind that gets told so people learn.',
          critical_fail: 'The hydraulics cascade. You have 3 seconds to decide. You eject at low altitude, barely enough for the chute to deploy. The aircraft is gone. You\'re alive. Some days that\'s the whole mission.',
        },
        aiGenerated: true,
      },
      {
        id: 'epilogue',
        type: 'epilogue',
        title: 'The Record',
        beat: 'Epilogue',
        text: `The debrief lasts six hours. The data cards take three days to analyze. At the end of it, Col. Hargrove puts a single note in your personnel file.\n\nYou don't see what it says.\n\nBut you know what kind of pilot you are now. You've always known. The envelope just confirmed it.`,
      },
    ],
  },

  'C-02': {
    id: 'C-02',
    title: 'Mission Critical',
    archetype: 'Flight Director',
    primaryStats: ['ALTITUDE', 'RANGE', 'PAYLOAD'],
    setting: 'Mission Control, Johnson Space Center → Lunar orbit → Mars transit',
    tagline: 'The call that saves the crew versus the call that follows the protocol.',
    badge: '🚀',
    available: true,
    baseStats: {
      altitude: 12, velocity: 9, payload: 12, range: 11, resilience: 10, maneuver: 9,
    },
    scenes: [
      {
        id: 'prologue',
        type: 'choice',
        title: 'Day One, Console',
        beat: 'Prologue',
        aiGenerated: false,
        text: `The fluorescent hum of Mission Control is the same at 2 AM as it is at noon. You've just been handed your badge — Flight Director trainee, Johnson Space Center. The console smells like stale coffee and decades of high-stakes decisions.\n\nYour supervisor, Flight Director Chen Wei, sets down a stack of flight rules and asks the question everyone gets asked on day one:\n\n"Why the chair? Half the candidates your age wanted to fly. Why did you choose the room instead of the cockpit?"`,
        choices: [
          {
            key: 'couldnt_fly',
            label: "Couldn't get flight status — color vision. But I could see everything from the console that the pilots couldn't.",
            statDeltas: { payload: 2, range: 1, velocity: -1 },
          },
          {
            key: 'chose_chair',
            label: "I flew. Then I realized one pilot makes one call. A Flight Director makes every call.",
            statDeltas: { altitude: 2, maneuver: 1, resilience: -1 },
          },
        ],
      },
      {
        id: 'scene1',
        type: 'choice',
        title: 'The Sim',
        beat: 'Scene 1',
        aiGenerated: false,
        text: `SIMULATION. The word is on every screen but your hands don't care. A Lunar Gateway resupply mission, two minutes from LOI burn, and your propulsion controller is calling a fuel pressure anomaly.\n\nThe sim instructor is watching. The anomaly is in a gray zone — the flight rules allow either call. Your propulsion lead, Dr. Amara Osei, has run this anomaly in the high-fidelity sim eighteen times. She says go. The book says nominal is 340 PSI. You're reading 327.\n\nYou have forty seconds.`,
        choices: [
          {
            key: 'book',
            label: 'Call it by the book. 327 is below nominal. Abort the burn. Explain later.',
            statDeltas: { payload: 2, resilience: 1, maneuver: -1 },
          },
          {
            key: 'gut',
            label: "Trust Amara. She's run this eighteen times. Go for ignition.",
            statDeltas: { range: 2, altitude: 1, payload: -1 },
          },
        ],
      },
      {
        id: 'scene2',
        type: 'choice',
        title: 'The Anomaly',
        beat: 'Scene 2',
        aiGenerated: true,
        fallbackText: `Twelve hours into the mission, your guidance officer flags something. The nav solution is drifting — 0.04 degrees per hour. Tiny. Below alarm threshold. But it's consistent.\n\nThe computer says nominal. Your guidance officer, a twenty-two year veteran named Marcus Tran, says something is wrong. He can't tell you what. He just knows the signature.\n\n"The computer passed it," you say. "I know," Marcus says. "It still looks wrong."`,
        choices: [
          {
            key: 'engineer',
            label: "Pull Marcus off the console. Let him dig into the data. You hold the room while he works.",
            statDeltas: { range: 2, altitude: 1, velocity: -1 },
          },
          {
            key: 'computer',
            label: "Log the observation. Trust the computer. Marcus is experienced but the data is the data.",
            statDeltas: { payload: 2, maneuver: 1, range: -1 },
          },
        ],
      },
      {
        id: 'signal_log',
        type: 'signal_log',
        title: 'Save Your Progress',
        beat: 'Scene 3',
      },
      {
        id: 'scene4',
        type: 'choice',
        title: 'The Handoff',
        beat: 'Scene 4',
        aiGenerated: true,
        fallbackText: `Flight Director Chen Wei leaves the console at hour eighteen. Scheduled rest rotation. Except she doesn't look rested — she looks like she's handing you something that weighs more than she's letting on.\n\n"Lunar orbit insertion is in four hours," she says quietly, headset half-off. "The crew trusts you. The room trusts you. I trust you. But the call on the GO/NO-GO is yours now. Not a simulation."\n\nShe pauses at the door. "You'll want to ask me to stay. Don't."`,
        choices: [
          {
            key: 'step_up',
            label: "Step up immediately. Thank her. Take the console. You were ready three hours ago.",
            statDeltas: { altitude: 2, resilience: 2, range: -1 },
          },
          {
            key: 'ask_second',
            label: "Ask for a ninety-second handoff brief. You're ready, but you want to own the open items before she walks.",
            statDeltas: { payload: 2, maneuver: 1, altitude: -1 },
          },
        ],
      },
      {
        id: 'boss',
        type: 'boss',
        title: 'GO / NO-GO',
        beat: 'Boss Moment',
        rollStats: ['altitude', 'payload'],
        setup: `Lunar orbit insertion in T-minus four minutes.\n\nEverything is nominal. Except one thing: your inertial measurement unit is showing a 0.03% deviation that wasn't there six hours ago. It's below the abort threshold. The flight rules say GO.\n\nBut Marcus's anomaly from twelve hours ago is still unexplained. And if the IMU is drifting, the burn will put the crew in the wrong orbit. Not wrong enough to fail. Wrong enough to strand them.\n\nThe crew is at the window. They can see the Moon.\n\nYour call.`,
        rollLabel: 'Roll ALTITUDE + PAYLOAD',
        fallbackOutcomes: {
          critical_success: "GO. You call it with seventeen seconds to spare. The burn is perfect. The orbit is textbook. Three days later, Marcus finds the IMU anomaly root cause — a thermal expansion edge case that had never been documented. You put it in the flight rules.",
          success: "GO. The burn executes. There's a 0.8-second correction burn six hours later that wasn't in the timeline, but the orbit is right and the crew is safe. The debrief lasts four hours. You answer every question.",
          fail: "NO-GO. You scrub the burn. The crew holds in transfer orbit for eighteen hours while engineering digs into the IMU data. They find nothing wrong. The mission continues late, over budget, with a crew that spent a day longer in zero-g than planned. You're not wrong. You'll never know if you were right.",
          critical_fail: "GO — and the burn is long by 1.2 seconds. The orbit is recoverable but the correction cost them 40% of their contingency propellant. The crew makes it. The review board makes a finding. Your name is in it. You learn things about decision-making under uncertainty that you could not have learned any other way.",
        },
        aiGenerated: true,
      },
      {
        id: 'epilogue',
        type: 'epilogue',
        title: 'The Call',
        beat: 'Epilogue',
        text: `The mission debrief is ninety-seven slides. Your GO/NO-GO call is on slide forty-two.\n\nYou've read the finding fourteen times. You'd make the same call again. Not because you were right. Because the alternative was a different kind of wrong, and you knew it in the moment.\n\nFlight Director Chen Wei sends you a single message after the board closes: "That's what the chair is for."`,
      },
    ],
  },
};